### ISSUE TITLE
Discard the unclassified root's son

### ISSUE THREAD

**Issue by agarciamontoro** [ohnosequences/db.taxonomy#12]
Just below the `root` there is an `unclassified` node that shall be discarded from the very beginning of the process.

**Comment by agarciamontoro** [comment]
Quick question here (@rtobes, @eparejatobes). The first levels of the NCBI taxonomy are the following:

```
12884   -> Viroids
        265963  -> unclassified viroids
        185751  -> Pospiviroidae
        185752  -> Avsunviroidae
10239   -> Viruses
        35325   -> dsRNA viruses
        439488  -> ssRNA viruses
        552364  -> unclassified virophages
        451344  -> unclassified archaeal viruses
        12333   -> unclassified bacterial viruses
        1425366 -> Virus-associated RNAs
        12429   -> unclassified viruses
        35268   -> Retro-transcribing viruses
        2080735 -> DNA viruses
        12877   -> Satellites
        35237   -> dsDNA viruses, no RNA stage
        186616  -> environmental samples
        1922347 -> unclassified RNA viruses
        29258   -> ssDNA viruses
        686617  -> unassigned viruses
131567  -> cellular organisms
        2157    -> Archaea
        2       -> Bacteria
        2759    -> Eukaryota
28384   -> other sequences
        81077   -> artificial sequences
        2671    -> integrons
        31896   -> midivariant sequence
        164974  -> stable RNAs
        2673    -> insertion sequences
        2387    -> transposons
        31897   -> promoter consensus sequence
        36549   -> plasmids
12908   -> unclassified sequences
        37965   -> hybrid
        36469   -> prion
        1515699 -> miscellaneous sequences
        1768868 -> collection
        1306155 -> mixed culture
        32644   -> unidentified
        704107  -> mixed libraries
        684672  -> mixed EST libraries
        151659  -> environmental samples
        1427524 -> mixed sample
        1566732 -> enrichment cultures
        408169  -> metagenomes
```

We only need `Archaea` and `Bacteria` under `cellular organisms`, right? Or do we need anything else?

**Comment by rtobes** [comment]
Yes,  we only need:
- Archaea (taxID 2157)
- Bacteria (taxID 2)

**Comment by agarciamontoro** [comment]
Great, thanks!

**Comment by eparejatobes** [comment]
wait wait wait please don't remove anything for now.

**Comment by agarciamontoro** [comment]
> wait wait wait please don't remove anything for now.

Ok ok ok, it's not that I can go to NCBI FTP and delete everything! :rofl: 

What else do we need?

**Comment by ncordon** [comment]
Can this be closed @agarciamontoro ? I think yes since we are spliting the full tree into 3 subtrees now (?)

**Comment by agarciamontoro** [comment]
Mmmmm, I don't really know, when we had this discussion we already knew we wanted to split the full tree into 3 subtrees.

@eparejatobes, do we need viroids, viruses, eukaryotas and everything else? Or should we store in our tree only Archaea and Bacteria?

**Comment by agarciamontoro** [comment]
I guess that in the future we may need to use nodes other than Archaea and Bacteria, so maybe we should keep everything as it is, even if for 16S we are only using those two branches.

In the meanwhile, we are assuming we will store everything, but I would like to have @eparejatobes confirmation, as the removal of all the other nodes would ease some of the future computations.

**Comment by agarciamontoro** [comment]
We have discussed this and concluded that we need every node in the raw data, not only Archaea and Bacteria.
