### ISSUE TITLE
Convert NCBI FTP file to custom format

### ISSUE THREAD

**Issue by agarciamontoro** [ohnosequences/db.taxonomy#5]
We need some code to convert the original tree from NCBI FTP to the custom format specified in #4.

Needs #4.

**Comment by eparejatobes** [comment]
See [bio4j/data.ncbitaxonomy](https://github.com/bio4j/data.ncbitaxonomy) (I completely forgot about this)

**Comment by agarciamontoro** [comment]
Needs ohnosequences/db.ncbitaxonomy#2 

The code in this repo will be similar to the one in db.rna16s.
