### ISSUE TITLE
Input NCBI Taxonomy Tree integrity checks

### ISSUE THREAD

**Issue by eparejatobes** [ohnosequences/db.taxonomy#9]
- [x] no cycles
- [x] no orphan nodes
- [x] only one parent (checked by construction I guess)
- [x] only one root
- [ ] ...

**Comment by eparejatobes** [comment]
comes from ohnosequences/db.ncbitaxonomy#3.

**Comment by ncordon** [comment]
Okay, I am going to close this and integrate it in https://github.com/ohnosequences/db.ncbitaxonomy/pull/19, which is the place where we intend that the full tree is generated
